name: CI

on: 
  push:
    branches:
      - developer
      - main
  pull_request:
    branches:
      - developer
      - main

jobs:
  flutter_test:
    name: Run Flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up token
        env:
          GITHUB_TOKEN: ${{ secrets.MY_CUSTOM_TOKEN }}
        run: |
          echo "Token configurado"

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 0